const parameters = {
  'chrome-phone-test': `--tags @phone --world-parameters '${JSON.stringify({ platform: 'chrome-phone-test', width: 520, height: 920 })}'`,
  'chrome-phone-dev': `--tags @phone --world-parameters '${JSON.stringify({ platform: 'chrome-phone-dev', width: 520, height: 920 })}'`,
  'chrome-desktop-dev': `--tags @desktop --world-parameters '${JSON.stringify({ platform: 'chrome-desktop-dev', width: 1800, height: 1180 })}'`,
  'chrome-desktop-test': `--tags @desktop --world-parameters '${JSON.stringify({ platform: 'chrome-desktop-test', width: 1070, height: 1180 })}'`,
  'chrome-desktop-test-ben': `--tags @Ben --world-parameters '${JSON.stringify({ platform: 'chrome-desktop-test', width: 1070, height: 1180 })}'`,
  'chrome-desktop-test-martin': `--tags @Martin --world-parameters '${JSON.stringify({ platform: 'chrome-desktop-test', width: 1020, height: 1180 })}'`,
  'chrome-phone-test-martin': `--tags @Martin --world-parameters '${JSON.stringify({ platform: 'chrome-phone-test', width: 520, height: 920 })}'`,
  'chrome-tablet-test-martin': `--tags @Martin --world-parameters '${JSON.stringify({ platform: 'chrome-tablet-test', width: 520, height: 920 })}'`,
  'chrome-desktop-test-smoke-dev': `--tags @Smoke_dev --world-parameters '${JSON.stringify({ platform: 'chrome-desktop-test', width: 1020, height: 1180 })}'`,
  'chrome-desktop-test-smoke-test': `--tags @Smoke_test --world-parameters '${JSON.stringify({ platform: 'chrome-desktop-test', width: 1020, height: 1180 })}'`,
  'chrome-desktop-test-smoke-preprod': `--tags @Smoke_preprod --world-parameters '${JSON.stringify({ platform: 'chrome-desktop-test', width: 1020, height: 1180 })}'`,
  'chrome-desktop-test-smoke-prod': `--tags @Smoke_prod --world-parameters '${JSON.stringify({ platform: 'chrome-desktop-test', width: 1020, height: 1180 })}'`,
  'chrome-phone-test-smoke': `--tags @Smoke --world-parameters '${JSON.stringify({ platform: 'chrome-phone-test', width: 520, height: 920 })}'`,
  'chrome-tablet-test-smoke': `--tags @Smoke --world-parameters '${JSON.stringify({ platform: 'chrome-tablet-test', width: 520, height: 920 })}'`,
  'chrome-desktop-test-userresearch': `--tags @UserResearch --world-parameters '${JSON.stringify({ platform: 'chrome-desktop-test', width: 1020, height: 1180 })}'`,
  'chrome-desktop-headless-test': `--tags @desktop --world-parameters '${JSON.stringify({ platform: 'chrome-desktop-headless-test', width: 1800, height: 1180 })}'`,
  'chrome-tablet-dev': `--tags @tablet --world-parameters '${JSON.stringify({ platform: 'chrome-tablet-dev', width: 1050, height: 850 })}'`,
  'chrome-tablet-test': `--tags @tablet --world-parameters '${JSON.stringify({ platform: 'chrome-tablet-test', width: 1050, height: 850 })}'`,
  'firefox-desktop-dev': `--tags @desktop --world-parameters '${JSON.stringify({ platform: 'firefox-desktop-dev', width: 1800, height: 1180 })}'`,
  'firefox-desktop-test': `--tags @desktop --world-parameters '${JSON.stringify({ platform: 'firefox-desktop-test', width: 1800, height: 1180 })}'`,
  'firefox-desktop-test-smoke-dev': `--tags @Smoke_dev --world-parameters '${JSON.stringify({ platform: 'firefox-desktop-test', width: 1800, height: 1180 })}'`,
  'firefox-desktop-test-smoke-dev-mcpsr': `--tags @Smoke_dev_MCPSR --world-parameters '${JSON.stringify({ platform: 'firefox-desktop-test', width: 1800, height: 1180 })}'`,
  'firefox-desktop-test-smoke-dev-mcpgensr': `--tags @Smoke_dev_MCPGenSR --world-parameters '${JSON.stringify({ platform: 'firefox-desktop-test', width: 1800, height: 1180 })}'`,
  'firefox-desktop-test-smoke-dev-mcpbespoke': `--tags @Smoke_dev_MCPBespoke_direct --world-parameters '${JSON.stringify({ platform: 'firefox-desktop-test', width: 1800, height: 1180 })}'`,
  'firefox-desktop-test-smoke-test': `--tags @Smoke_test --world-parameters '${JSON.stringify({ platform: 'firefox-desktop-test', width: 1800, height: 1180 })}'`,
  'firefox-desktop-test-smoke-preprod': `--tags @Smoke_preprod --world-parameters '${JSON.stringify({ platform: 'firefox-desktop-test', width: 1800, height: 1180 })}'`,
  'firefox-desktop-test-smoke-prod': `--tags @Smoke_prod --world-parameters '${JSON.stringify({ platform: 'firefox-desktop-test', width: 1800, height: 1180 })}'`,
  'ie-desktop-dev': `--tags @desktop --world-parameters '${JSON.stringify({ platform: 'ie-desktop-dev', width: 1800, height: 1180 })}'`,
  'ie-desktop-test': `--tags @desktop --world-parameters '${JSON.stringify({ platform: 'ie-desktop-test', width: 1800, height: 1180 })}'`
}

module.exports = parameters
