Feature: Tests to check Standard rules which are applicable online and SR's which are applicable for download form

    @Smoke_dev
    @Smoke_test
    Scenario Outline: As a user, I should be able to fill the forms online for the permits which are available for apply online
        Given the application has been launched
        And I start a new application
        #And I select Standard rules as the permit type
        And I select <PermitHolder> as the permit holder
        And I select <PermitCategory> as the permit category
        And I select <Permit> as the permit number
        And I check <Cost> on Cost and processing time page
        And I confirm I meet the rules <Link>
        Examples:
            | PermitHolder                  | PermitCategory                                                                         | Permit              | Cost  | Link                                                                                                                                                     |
            | Limited company               | Car and vehicle dismantling                                                            | SR2015 No 13        | 3,926 | https://www.gov.uk/government/publications/sr2015-no13-75kte-vehicle-storage-depollution-and-dismantling-authorised-treatment-facility                   |
            | Sole trader                   | Metal recycling, scrap metal and WEEE - not cars or vehicles                           | SR2015 No 14        | 3,926 | https://www.gov.uk/government/publications/sr2015-no14-75kte-metal-recycling-site                                                                        |
            | Limited liability partnership | Deposit for recovery                                                                   | SR2015 No 39        | 3,872 | https://www.gov.uk/government/publications/sr2015-no39-use-of-waste-in-a-deposit-for-recovery-operation                                                  |
            | Individual                    | Composting, sewage or sludge treatment, biogas                                         | SR2010 No 14        | 2,641 | https://www.gov.uk/government/publications/sr2010-no14-500t-composting-biodegradable-waste                                                               |
            | Partnership                   | Electrical insulating oil storage                                                      | SR2012 No 15        | 2,641 | https://www.gov.uk/government/publications/sr2012-no15-storage-of-electrical-insulating-oils                                                             |
            | Limited company               | Anaerobic digestion including storing digestate                                        | SR2012 No 12        | 2,641 | https://www.gov.uk/government/publications/sr2012-no12-anaerobic-digestion-facility-including-use-of-the-resultant-biogas-waste-recovery-operation       |
            | Limited company               | Anaerobic digestion including storing digestate                                        | SR2012 No 10        | 2,641 | https://www.gov.uk/government/publications/sr2012-no10-on-farm-anaerobic-digestion-facility-using-farm-wastes-only-including-use-of-the-resultant-biogas |
            | Sole trader                   | Car and vehicle dismantling                                                            | SR2015 No 18        | 3,926 | https://www.gov.uk/government/publications/sr2015-no18-metal-recycling-vehicle-storage-depollution-and-dismantling-facility                              |
            | Limited liability partnership | Car and vehicle dismantling                                                            | SR2015 No 17        | 3,926 | https://www.gov.uk/government/publications/sr2015-no17-vehicle-storage-depollution-and-dismantling-authorised-treatment-facility                         |
            | Individual                    | Composting, sewage or sludge treatment, biogas                                         | SR2009 No 4         | 2,641 | https://www.gov.uk/government/publications/sr2009-no4-combustion-of-biogas-in-engines-at-a-sewage-treatment-works                                        |
            | Individual                    | Composting, sewage or sludge treatment, biogas                                         | SR2011 No 1         | 2,641 | https://www.gov.uk/government/publications/sr2011-no1-500t-composting-biodegradable-waste-in-open-and-closed-systems                                     |
            | Individual                    | Composting, sewage or sludge treatment, biogas                                         | SR2012 No 3         | 2,641 | https://www.gov.uk/government/publications/sr2012-no3-composting-in-closed-systems                                                                       |
            | Individual                    | Composting, sewage or sludge treatment, biogas                                         | SR2012 No 7         | 2,641 | https://www.gov.uk/government/publications/sr2012-no7-composting-in-open-systems                                                                         |
            | Individual                    | Composting, sewage or sludge treatment, biogas                                         | SR2015 No 12        | 3,926 | https://www.gov.uk/government/publications/sr2015-no12-75kte-non-hazardous-mechanical-biological-aerobic-treatment-facility                              |
            | Individual                    | Composting, sewage or sludge treatment, biogas                                         | SR2008 No 19 250kte | 2,641 | https://www.gov.uk/government/publications/sr2008-no19-250kte-non-hazardous-sludge-biological-chemical-and-physical-treatment-site                       |
            | Individual                    | Composting, sewage or sludge treatment, biogas                                         | SR2008 No 19 75kte  | 2,641 | https://www.gov.uk/government/publications/sr2008-no19-75kte-non-hazardous-sludge-biological-chemical-and-physical-treatment-site                        |
            | Individual                    | Deposit for recovery                                                                   | SR2015 No 39        | 3,872 | https://www.gov.uk/government/publications/sr2015-no39-use-of-waste-in-a-deposit-for-recovery-operation                                                  |
            | Individual                    | Electrical insulating oil storage                                                      | SR2012 No 15        | 2,641 | https://www.gov.uk/government/publications/sr2012-no15-storage-of-electrical-insulating-oils                                                             |
            | Individual                    | Metal recycling, scrap metal and WEEE - not cars or vehicles                           | SR2015 No 14        | 3,926 | https://www.gov.uk/government/publications/sr2015-no14-75kte-metal-recycling-site                                                                        |
            | Individual                    | Metal recycling, scrap metal and WEEE - not cars or vehicles                           | SR2015 No 16        | 3,926 | https://www.gov.uk/government/publications/sr2015-no16-metal-recycling-site                                                                              |
            | Individual                    | Metal recycling, scrap metal and WEEE - not cars or vehicles                           | SR2008 No 22        | 3,926 | https://www.gov.uk/government/publications/sr2008-no22-75kte-storage-of-furnace-ready-scrap-metal-for-recovery                                           |
            | Individual                    | Metal recycling, scrap metal and WEEE - not cars or vehicles                           | SR2009 No 7         | 3,926 | https://www.gov.uk/government/publications/sr2009-no7-storage-of-furnace-ready-scrap-metal-for-recovery                                                  |
            | Individual                    | Metal recycling, scrap metal and WEEE - not cars or vehicles                           | SR2015 No 15        | 3,926 | https://www.gov.uk/government/publications/sr2015-no15-75kte-weee-authorised-treatment-facility-excluding-ozone-depleting-substances                     |
            | Individual                    | Mining, oil and gas                                                                    | SR2014 No 2         | 2,641 | https://www.gov.uk/government/publications/sr2014-no-2-the-management-of-extractive-waste                                                                |
            | Individual                    | Mobile plant for land-spreading or treatment                                           | SR2010 No 4         | 2,641 | https://www.gov.uk/government/publications/sr2010-no4-mobile-plant-for-land-spreading                                                                    |
            | Individual                    | Mobile plant for land-spreading or treatment                                           | SR2010 No 6         | 2,641 | https://www.gov.uk/government/publications/sr2010-no6-mobile-plant-for-land-spreading-of-sewage-sludge                                                   |
            | Individual                    | Mobile plant for land-spreading or treatment                                           | SR2010 No 5         | 2,641 | https://www.gov.uk/government/publications/sr2010-no5-mobile-plant-for-reclamation-restoration-or-improvement-of-land                                    |
            | Individual                    | Mobile plant for land-spreading or treatment                                           | SR2008 No 27        | 2,641 | https://www.gov.uk/government/publications/standard-rules-sr2008-number-27                                                                               |
            | Individual                    | Mobile plant for land-spreading or treatment                                           | SR2010 No 11        | 2,641 | https://www.gov.uk/government/publications/sr2010-number-11                                                                                              |
            | Individual                    | Storage or treatment of waste - recycling, dredgings, clinical, soil or wood treatment | SR2015 No 21        | 3,926 | https://www.gov.uk/government/publications/sr2015-no21-75kte-materials-recycling-facility                                                                |
            | Individual                    | Storage or treatment of waste - recycling, dredgings, clinical, soil or wood treatment | SR2010 No 18        | 2,641 | https://www.gov.uk/government/publications/sr2010-no18-storage-and-treatment-of-dredgings-for-recovery                                                   |
            | Individual                    | Storage or treatment of waste - recycling, dredgings, clinical, soil or wood treatment | SR2010 No 17        | 2,641 | https://www.gov.uk/government/publications/sr2010-no17-storage-of-digestate-from-anaerobic-digestion-plants                                              |
            | Individual                    | Storage or treatment of waste - recycling, dredgings, clinical, soil or wood treatment | SR2013 No 1         | 2,641 | https://www.gov.uk/government/publications/sr2013-no-1-treatment-of-100-ty-of-clinical-and-healthcare-waste                                              |
            | Individual                    | Storage or treatment of waste - recycling, dredgings, clinical, soil or wood treatment | SR2010 No 12        | 2,641 | https://www.gov.uk/government/publications/sr2010-number-12                                                                                              |
            | Individual                    | Storage or treatment of waste - recycling, dredgings, clinical, soil or wood treatment | SR2015 No 23        | 3,926 | https://www.gov.uk/government/publications/sr2015-no23-treatment-of-waste-wood-for-recovery                                                              |
            | Individual                    | Storage or treatment of waste - recycling, dredgings, clinical, soil or wood treatment | SR2015 No 24        | 3,926 | https://www.gov.uk/government/publications/sr2015-no24-use-of-waste-to-manufacture-timber-or-construction-products                                       |
            | Individual                    | Waste transfer station or amenity site with or without treatment                       | SR2008 No 9         | 2,641 | https://www.gov.uk/government/publications/sr2008-no9-asbestos-waste-transfer-station                                                                    |
            | Individual                    | Waste transfer station or amenity site with or without treatment                       | SR2015 No 4         | 3,926 | https://www.gov.uk/government/publications/sr2015-no4-75kte-household-commercial-and-industrial-waste-transfer-station                                   |
            | Individual                    | Waste transfer station or amenity site with or without treatment                       | SR2015 No 9         | 3,926 | https://www.gov.uk/government/publications/sr2015-no9-household-commercial-and-industrial-waste-transfer-station-with-asbestos-storage-no-building       |
            | Individual                    | Waste transfer station or amenity site with or without treatment                       | SR2015 No 6         | 3,926 | https://www.gov.uk/government/publications/sr2015-no6-75kte-household-commercial-and-industrial-waste-transfer-station-with-treatment                    |
            | Individual                    | Waste transfer station or amenity site with or without treatment                       | SR2015 No 7         | 3,926 | https://www.gov.uk/government/publications/sr2015-no7-household-commercial-and-industrial-waste-transfer-station-with-treatment-no-building              |
# | Individual                    | Waste transfer station or amenity site with or without treatment                       | SR2015 No 10        | NO MONEY | link                                                                                                                                                     |
# | Individual                    | Waste transfer station or amenity site with or without treatment                       | SR2015 No 11        | NO MONEY | link                                                                                                                                                     |
# | Individual                    | Waste transfer station or amenity site with or without treatment                       | SR2015 No 20        | NO MONEY | link                                                                                                                                                     |
# | Individual                    | Waste transfer station or amenity site with or without treatment                       | SR2015 No 19        | NO MONEY | link                                                                                                                                                     |
# | Individual                    | Water discharges                                                                       | NO SR               | NO MONEY | link                                                                                                                                                     |


# Scenario Outline: As a user, I should be able to download the forms for the permits where i cannot apply online
#   #| Individual                    | Composting, sewage or sludge treatment, biogas                                         | SR2012 No 4         | 2,641    | link                                                                                                                                                     |
#  #| Individual                    | Composting, sewage or sludge treatment, biogas                                         | SR2012 No 8         | 2,641    | link                                                                                                                                                     |
#  #| Individual                    | Composting, sewage or sludge treatment, biogas                                         | SR2009 No 3         | 2,641    | link                                                                                                                                                     |
#   | Individual                    | Flood risk activities                                                                  | No SR               | No MONEY | link                                                                                                                                                     |
#    | Individual                    | Metal recycling, scrap metal and WEEE - not cars or vehicles                           | SR2015 No 3         | 2,641    | link                                                                                                                                                     |
# | Individual                    | Mining, oil and gas                                                                    | SR2009 No 8         | 2,641    | link                                                                                                                                                     |
#  | Individual                    | Mining, oil and gas                                                                    | SR2015 No 2         | 2,641    | link                                                                                                                                                     |
#  | Individual                    | Mining, oil and gas                                                                    | SR2015 No 1         | 2,641    | link                                                                                                                                                     |
#  | Individual                    | Radioactive substances for non-nuclear sites                                           | NO SR               | NO MONEY | link                                                                                                                                                     |
# | Individual                    | Storage or treatment of waste - recycling, dredgings, clinical, soil or wood treatment | SR2009 No 2         | 2,641    | link                                                                                                                                                     |
# | Individual                    | Storage or treatment of waste - recycling, dredgings, clinical, soil or wood treatment | SR2015 No 22        | 2,641    | link                                                                                                                                                     |
#| Individual                    | Storage or treatment of waste - recycling, dredgings, clinical, soil or wood treatment | SR2012 No 13        | 2,641    | link                                                                                                                                                     |
#  | Individual                    | Waste transfer station or amenity site with or without treatment                       | SR2015 No 5         | NO MONEY | link                                                                                                                                                     |
#  | Individual                    | Waste transfer station or amenity site with or without treatment                       | SR2015 No 8         | NO MONEY | link                                                                                                                                                     |




