Feature: Tests to check Standard rules which are applicable online and SR's which are applicable for download form

  @Smoke_dev
  @Smoke_test
  Scenario Outline: As a user, I should be able to fill the forms online for the online permit <Permit>
    Given the application has been launched
    And I start a new application
    And I select Standard rules as the permit type
    And I select <PermitCategory> as the permit category
    And I select <Permit> as the permit number
    And I check <Cost> on Cost and processing time page
    And I confirm I meet the rules <Link>
    Examples:
      | PermitCategory                                                                         | Permit              | Cost  | Link                                                                                                                                                              |
      | Car and vehicle dismantling                                                            | SR2015 No 13        | 3,926 | https://www.gov.uk/government/publications/sr2015-no13-75kte-vehicle-storage-depollution-and-dismantling-authorised-treatment-facility                            |
      | Metal recycling, scrap metal and WEEE - not cars or vehicles                           | SR2015 No 14        | 3,926 | https://www.gov.uk/government/publications/sr2015-no14-75kte-metal-recycling-site                                                                                 |
      | Deposit for recovery                                                                   | SR2015 No 39        | 3,872 | https://www.gov.uk/government/publications/sr2015-no39-use-of-waste-in-a-deposit-for-recovery-operation                                                           |
      | Composting, sewage or sludge treatment, biogas                                         | SR2010 No 14        | 2,641 | https://www.gov.uk/government/publications/sr2010-no14-500t-composting-biodegradable-waste                                                                        |
      | Electrical insulating oil storage                                                      | SR2012 No 15        | 2,641 | https://www.gov.uk/government/publications/sr2012-no15-storage-of-electrical-insulating-oils                                                                      |
      | Anaerobic digestion including storing digestate                                        | SR2012 No 12        | 2,641 | https://www.gov.uk/government/publications/sr2012-no12-anaerobic-digestion-facility-including-use-of-the-resultant-biogas-waste-recovery-operation                |
      | Anaerobic digestion including storing digestate                                        | SR2012 No 10        | 2,641 | https://www.gov.uk/government/publications/sr2012-no10-on-farm-anaerobic-digestion-facility-using-farm-wastes-only-including-use-of-the-resultant-biogas          |
      | Car and vehicle dismantling                                                            | SR2015 No 18        | 3,926 | https://www.gov.uk/government/publications/sr2015-no18-metal-recycling-vehicle-storage-depollution-and-dismantling-facility                                       |
      | Car and vehicle dismantling                                                            | SR2015 No 17        | 3,926 | https://www.gov.uk/government/publications/sr2015-no17-vehicle-storage-depollution-and-dismantling-authorised-treatment-facility                                  |
      | Composting, sewage or sludge treatment, biogas                                         | SR2011 No 1         | 2,641 | https://www.gov.uk/government/publications/sr2011-no1-500t-composting-biodegradable-waste-in-open-and-closed-systems                                              |
      | Composting, sewage or sludge treatment, biogas                                         | SR2012 No 3         | 2,641 | https://www.gov.uk/government/publications/sr2012-no3-composting-in-closed-systems                                                                                |
      | Composting, sewage or sludge treatment, biogas                                         | SR2012 No 7         | 2,641 | https://www.gov.uk/government/publications/sr2012-no7-composting-in-open-systems                                                                                  |
      | Composting, sewage or sludge treatment, biogas                                         | SR2015 No 12        | 3,926 | https://www.gov.uk/government/publications/sr2015-no12-75kte-non-hazardous-mechanical-biological-aerobic-treatment-facility                                       |
      | Composting, sewage or sludge treatment, biogas                                         | SR2008 No 19 250kte | 2,641 | https://www.gov.uk/government/publications/sr2008-no19-250kte-non-hazardous-sludge-biological-chemical-and-physical-treatment-site                                |
      | Composting, sewage or sludge treatment, biogas                                         | SR2008 No 19 75kte  | 2,641 | https://www.gov.uk/government/publications/sr2008-no19-75kte-non-hazardous-sludge-biological-chemical-and-physical-treatment-site                                 |
      | Deposit for recovery                                                                   | SR2015 No 39        | 3,872 | https://www.gov.uk/government/publications/sr2015-no39-use-of-waste-in-a-deposit-for-recovery-operation                                                           |
      | Electrical insulating oil storage                                                      | SR2012 No 15        | 2,641 | https://www.gov.uk/government/publications/sr2012-no15-storage-of-electrical-insulating-oils                                                                      |
      | Metal recycling, scrap metal and WEEE - not cars or vehicles                           | SR2015 No 14        | 3,926 | https://www.gov.uk/government/publications/sr2015-no14-75kte-metal-recycling-site                                                                                 |
      | Metal recycling, scrap metal and WEEE - not cars or vehicles                           | SR2015 No 16        | 3,926 | https://www.gov.uk/government/publications/sr2015-no16-metal-recycling-site                                                                                       |
      | Metal recycling, scrap metal and WEEE - not cars or vehicles                           | SR2008 No 22        | 3,926 | https://www.gov.uk/government/publications/sr2008-no22-75kte-storage-of-furnace-ready-scrap-metal-for-recovery                                                    |
      | Metal recycling, scrap metal and WEEE - not cars or vehicles                           | SR2009 No 7         | 3,926 | https://www.gov.uk/government/publications/sr2009-no7-storage-of-furnace-ready-scrap-metal-for-recovery                                                           |
      | Metal recycling, scrap metal and WEEE - not cars or vehicles                           | SR2015 No 15        | 3,926 | https://www.gov.uk/government/publications/sr2015-no15-75kte-weee-authorised-treatment-facility-excluding-ozone-depleting-substances                              |
      | Mining, oil and gas                                                                    | SR2014 No 2         | 2,641 | https://www.gov.uk/government/publications/sr2014-no-2-the-management-of-extractive-waste                                                                         |
#      | Mobile plant for land-spreading or treatment                                           | SR2010 No 4         | 2,641 | https://www.gov.uk/government/publications/sr2010-no4-mobile-plant-for-land-spreading                                                                             |
#      | Mobile plant for land-spreading or treatment                                           | SR2010 No 6         | 2,641 | https://www.gov.uk/government/publications/sr2010-no6-mobile-plant-for-land-spreading-of-sewage-sludge                                                            |
#      | Mobile plant for land-spreading or treatment                                           | SR2010 No 5         | 2,641 | https://www.gov.uk/government/publications/sr2010-no5-mobile-plant-for-reclamation-restoration-or-improvement-of-land                                             |
#      | Mobile plant for land-spreading or treatment                                           | SR2008 No 27        | 2,641 | https://www.gov.uk/government/publications/standard-rules-sr2008-number-27                                                                                        |
#      | Mobile plant for land-spreading or treatment                                           | SR2010 No 11        | 2,641 | https://www.gov.uk/government/publications/sr2010-number-11                                                                                                       |
      | Storage or treatment of waste - recycling, dredgings, clinical, soil or wood treatment | SR2015 No 21        | 3,926 | https://www.gov.uk/government/publications/sr2015-no21-75kte-materials-recycling-facility                                                                         |
      | Storage or treatment of waste - recycling, dredgings, clinical, soil or wood treatment | SR2010 No 18        | 2,641 | https://www.gov.uk/government/publications/sr2010-no18-storage-and-treatment-of-dredgings-for-recovery                                                            |
      | Storage or treatment of waste - recycling, dredgings, clinical, soil or wood treatment | SR2010 No 17        | 2,641 | https://www.gov.uk/government/publications/sr2010-no17-storage-of-digestate-from-anaerobic-digestion-plants                                                       |
      | Storage or treatment of waste - recycling, dredgings, clinical, soil or wood treatment | SR2013 No 1         | 2,641 | https://www.gov.uk/government/publications/sr2013-no-1-treatment-of-100-ty-of-clinical-and-healthcare-waste                                                       |
      | Storage or treatment of waste - recycling, dredgings, clinical, soil or wood treatment | SR2010 No 12        | 2,641 | https://www.gov.uk/government/publications/sr2010-number-12                                                                                                       |
      | Storage or treatment of waste - recycling, dredgings, clinical, soil or wood treatment | SR2015 No 23        | 3,926 | https://www.gov.uk/government/publications/sr2015-no23-treatment-of-waste-wood-for-recovery                                                                       |
      | Storage or treatment of waste - recycling, dredgings, clinical, soil or wood treatment | SR2015 No 24        | 3,926 | https://www.gov.uk/government/publications/sr2015-no24-use-of-waste-to-manufacture-timber-or-construction-products                                                |
      | Waste transfer station or amenity site with or without treatment                       | SR2008 No 9         | 2,641 | https://www.gov.uk/government/publications/sr2008-no9-asbestos-waste-transfer-station                                                                             |
      | Waste transfer station or amenity site with or without treatment                       | SR2015 No 4         | 3,926 | https://www.gov.uk/government/publications/sr2015-no4-75kte-household-commercial-and-industrial-waste-transfer-station                                            |
      | Waste transfer station or amenity site with or without treatment                       | SR2015 No 9         | 3,926 | https://www.gov.uk/government/publications/sr2015-no9-household-commercial-and-industrial-waste-transfer-station-with-asbestos-storage-no-building                |
      | Waste transfer station or amenity site with or without treatment                       | SR2015 No 6         | 3,926 | https://www.gov.uk/government/publications/sr2015-no6-75kte-household-commercial-and-industrial-waste-transfer-station-with-treatment                             |
      | Waste transfer station or amenity site with or without treatment                       | SR2015 No 7         | 3,926 | https://www.gov.uk/government/publications/sr2015-no7-household-commercial-and-industrial-waste-transfer-station-with-treatment-no-building                       |
      | Waste transfer station or amenity site with or without treatment                       | SR2015 No 10        | 3,926 | https://www.gov.uk/government/publications/sr2015-no10-75kte-household-commercial-and-industrial-waste-transfer-station-with-treatment-and-asbestos-storage       |
      | Waste transfer station or amenity site with or without treatment                       | SR2015 No 11        | 3,926 | https://www.gov.uk/government/publications/sr2015-no11-household-commercial-and-industrial-waste-transfer-station-with-treatment-and-asbestos-storage-no-building |
      | Waste transfer station or amenity site with or without treatment                       | SR2015 No 20        | 3,926 | https://www.gov.uk/government/publications/sr2015-no20-75kte-non-hazardous-and-hazardous-household-waste-amenity-site                                             |
      | Waste transfer station or amenity site with or without treatment                       | SR2015 No 19        | 3,926 | https://www.gov.uk/government/publications/sr2015-no19-75kte-non-hazardous-household-waste-amenity-site                                                           |
      | Metal recycling, scrap metal and WEEE - not cars or vehicles                           | SR2015 No 3         | 3,926 | https://www.gov.uk/government/publications/sr2015-no3-metal-recycling-and-weee-authorised-treatment-facility-excluding-ozone-depleting-substances                 |
      | Storage or treatment of waste - recycling, dredgings, clinical, soil or wood treatment | SR2015 No 22        | 3,926 | https://www.gov.uk/government/publications/sr2015-no22-materials-recycling-facility-no-building                                                                   |
      | Waste transfer station or amenity site with or without treatment                       | SR2015 No 5         | 3,926 | https://www.gov.uk/government/publications/sr2015-no5-household-commercial-and-industrial-waste-transfer-station-no-building                                      |
      | Waste transfer station or amenity site with or without treatment                       | SR2015 No 8         | 3,926 | https://www.gov.uk/government/publications/sr2015-no8-75kte-household-commercial-and-industrial-waste-transfer-station-with-asbestos-storage                      |

  @wip
  @Smoke_dev
  @Smoke_test
  Scenario Outline: As a user, I should be able to download the forms for the offline permit: <Permit>
    Given the application has been launched
    And I start a new application
    And I select Standard rules as the permit type
    And I select <PermitCategory> as the permit category
    And I select <Permit> as the permit number
    Then I am on <PermitType> apply offline page with <Link> link
    Examples:
      | PermitCategory                                                                         | Permit       | PermitType                                                                                                                                                                | Link                                                                                                                                                 |
      | Composting, sewage or sludge treatment, biogas                                         | SR2012 No 4  | Apply for composting in closed systems - installation - SR2012 No 4                                                                                                       | https://www.gov.uk/government/collections/environmental-permit-application-forms-for-a-standard-permit-installations-mining-waste-or-waste-operation |
      | Composting, sewage or sludge treatment, biogas                                         | SR2012 No 8  | Apply for composting in open systems - installation - SR2012 No 8                                                                                                         | https://www.gov.uk/government/collections/environmental-permit-application-forms-for-a-standard-permit-installations-mining-waste-or-waste-operation |
      | Composting, sewage or sludge treatment, biogas                                         | SR2009 No 3  | Apply for low impact part a installation for the production of biodiesel - SR2009 No 3                                                                                    | https://www.gov.uk/government/collections/environmental-permit-application-forms-for-a-standard-permit-installations-mining-waste-or-waste-operation |
      | Mining, oil and gas                                                                    | SR2009 No 8  | Apply for management of inert wastes and unpolluted soil at mines and quarries - SR2009 No 8                                                                              | https://www.gov.uk/government/collections/environmental-permit-application-forms-for-a-standard-permit-installations-mining-waste-or-waste-operation |
      | Mining, oil and gas                                                                    | SR2015 No 2  | Apply for storage and handling of crude oil from onshore oil and gas - installation - SR2015 No 2                                                                         | https://www.gov.uk/government/collections/environmental-permit-application-forms-for-a-standard-permit-installations-mining-waste-or-waste-operation |
      | Mining, oil and gas                                                                    | SR2015 No 1  | Apply for the management of extractive waste, not including a waste facility, generated from onshore oil and gas prospecting excluding hydraulic fracturing - SR2015 No 1 | https://www.gov.uk/government/collections/environmental-permit-application-forms-for-a-standard-permit-installations-mining-waste-or-waste-operation |
      | Storage or treatment of waste - recycling, dredgings, clinical, soil or wood treatment | SR2009 No 2  | Apply for low impact part a installation for spent ion exchange resins - SR2009 No 2                                                                                      | https://www.gov.uk/government/collections/environmental-permit-application-forms-for-a-standard-permit-installations-mining-waste-or-waste-operation |
      | Storage or treatment of waste - recycling, dredgings, clinical, soil or wood treatment | SR2012 No 13 | Apply for treatment of incinerator bottom ash (iba) - installation - SR2012 No 13                                                                                         | https://www.gov.uk/government/collections/environmental-permit-application-forms-for-a-standard-permit-installations-mining-waste-or-waste-operation |

  @wip
  @Smoke_dev
  @Smoke_test
  Scenario Outline: As a user, I should be able to download the forms for the offline permit category: <PermitCategory>
    Given the application has been launched
    And I start a new application
    And I select Standard rules as the permit type
    And I select <PermitCategory> as the permit category
    Then I am on <PermitType> apply offline page with <Link> link
    Examples:
      | PermitCategory                               | PermitType                                                     | Link                                                                                                             |
      | Flood risk activities                        | Apply for flood risk activities permits                        | https://www.gov.uk/guidance/flood-risk-activities-environmental-permits#standard-rules-permits                   |
      | Water discharges                             | Apply for water discharges permits                             | https://www.gov.uk/government/collections/environmental-permit-application-forms-standard-permit-water-discharge |
      | Radioactive substances for non-nuclear sites | Apply for radioactive substances for non-nuclear sites permits | https://www.gov.uk/government/collections/radioactive-substances-regulation-for-non-nuclear-sites                |

  @Smoke_preprod
  @Smoke_prod
  Scenario Outline: As a user, I should be able to fill the forms online for the online permit <Permit>
    Given the application has been launched
    And I start a new application
        #And I select Standard rules as the permit type
    And I select <PermitCategory> as the permit category
    And I select <Permit> as the permit number
    And I check <Cost> on Cost and processing time page
    And I confirm I meet the rules <Link>
    Examples:
      | PermitCategory                                                                         | Permit              | Cost  | Link                                                                                                                                                              |
      | Car and vehicle dismantling                                                            | SR2015 No 13        | 3,926 | https://www.gov.uk/government/publications/sr2015-no13-75kte-vehicle-storage-depollution-and-dismantling-authorised-treatment-facility                            |
      | Metal recycling, scrap metal and WEEE - not cars or vehicles                           | SR2015 No 14        | 3,926 | https://www.gov.uk/government/publications/sr2015-no14-75kte-metal-recycling-site                                                                                 |
      | Deposit for recovery                                                                   | SR2015 No 39        | 3,872 | https://www.gov.uk/government/publications/sr2015-no39-use-of-waste-in-a-deposit-for-recovery-operation                                                           |
      | Composting, sewage or sludge treatment, biogas                                         | SR2010 No 14        | 2,641 | https://www.gov.uk/government/publications/sr2010-no14-500t-composting-biodegradable-waste                                                                        |
      | Electrical insulating oil storage                                                      | SR2012 No 15        | 2,641 | https://www.gov.uk/government/publications/sr2012-no15-storage-of-electrical-insulating-oils                                                                      |
      | Anaerobic digestion including storing digestate                                        | SR2012 No 12        | 2,641 | https://www.gov.uk/government/publications/sr2012-no12-anaerobic-digestion-facility-including-use-of-the-resultant-biogas-waste-recovery-operation                |
      | Anaerobic digestion including storing digestate                                        | SR2012 No 10        | 2,641 | https://www.gov.uk/government/publications/sr2012-no10-on-farm-anaerobic-digestion-facility-using-farm-wastes-only-including-use-of-the-resultant-biogas          |
      | Car and vehicle dismantling                                                            | SR2015 No 18        | 3,926 | https://www.gov.uk/government/publications/sr2015-no18-metal-recycling-vehicle-storage-depollution-and-dismantling-facility                                       |
      | Car and vehicle dismantling                                                            | SR2015 No 17        | 3,926 | https://www.gov.uk/government/publications/sr2015-no17-vehicle-storage-depollution-and-dismantling-authorised-treatment-facility                                  |
      | Composting, sewage or sludge treatment, biogas                                         | SR2011 No 1         | 2,641 | https://www.gov.uk/government/publications/sr2011-no1-500t-composting-biodegradable-waste-in-open-and-closed-systems                                              |
      | Composting, sewage or sludge treatment, biogas                                         | SR2012 No 3         | 2,641 | https://www.gov.uk/government/publications/sr2012-no3-composting-in-closed-systems                                                                                |
      | Composting, sewage or sludge treatment, biogas                                         | SR2012 No 7         | 2,641 | https://www.gov.uk/government/publications/sr2012-no7-composting-in-open-systems                                                                                  |
      | Composting, sewage or sludge treatment, biogas                                         | SR2015 No 12        | 3,926 | https://www.gov.uk/government/publications/sr2015-no12-75kte-non-hazardous-mechanical-biological-aerobic-treatment-facility                                       |
      | Composting, sewage or sludge treatment, biogas                                         | SR2008 No 19 250kte | 2,641 | https://www.gov.uk/government/publications/sr2008-no19-250kte-non-hazardous-sludge-biological-chemical-and-physical-treatment-site                                |
      | Composting, sewage or sludge treatment, biogas                                         | SR2008 No 19 75kte  | 2,641 | https://www.gov.uk/government/publications/sr2008-no19-75kte-non-hazardous-sludge-biological-chemical-and-physical-treatment-site                                 |
      | Deposit for recovery                                                                   | SR2015 No 39        | 3,872 | https://www.gov.uk/government/publications/sr2015-no39-use-of-waste-in-a-deposit-for-recovery-operation                                                           |
      | Electrical insulating oil storage                                                      | SR2012 No 15        | 2,641 | https://www.gov.uk/government/publications/sr2012-no15-storage-of-electrical-insulating-oils                                                                      |
      | Metal recycling, scrap metal and WEEE - not cars or vehicles                           | SR2015 No 14        | 3,926 | https://www.gov.uk/government/publications/sr2015-no14-75kte-metal-recycling-site                                                                                 |
      | Metal recycling, scrap metal and WEEE - not cars or vehicles                           | SR2015 No 16        | 3,926 | https://www.gov.uk/government/publications/sr2015-no16-metal-recycling-site                                                                                       |
      | Metal recycling, scrap metal and WEEE - not cars or vehicles                           | SR2008 No 22        | 3,926 | https://www.gov.uk/government/publications/sr2008-no22-75kte-storage-of-furnace-ready-scrap-metal-for-recovery                                                    |
      | Metal recycling, scrap metal and WEEE - not cars or vehicles                           | SR2009 No 7         | 3,926 | https://www.gov.uk/government/publications/sr2009-no7-storage-of-furnace-ready-scrap-metal-for-recovery                                                           |
      | Metal recycling, scrap metal and WEEE - not cars or vehicles                           | SR2015 No 15        | 3,926 | https://www.gov.uk/government/publications/sr2015-no15-75kte-weee-authorised-treatment-facility-excluding-ozone-depleting-substances                              |
      | Mining, oil and gas                                                                    | SR2014 No 2         | 2,641 | https://www.gov.uk/government/publications/sr2014-no-2-the-management-of-extractive-waste                                                                         |
#      | Mobile plant for land-spreading or treatment                                           | SR2010 No 4         | 2,641 | https://www.gov.uk/government/publications/sr2010-no4-mobile-plant-for-land-spreading                                                                             |
#      | Mobile plant for land-spreading or treatment                                           | SR2010 No 6         | 2,641 | https://www.gov.uk/government/publications/sr2010-no6-mobile-plant-for-land-spreading-of-sewage-sludge                                                            |
#      | Mobile plant for land-spreading or treatment                                           | SR2010 No 5         | 2,641 | https://www.gov.uk/government/publications/sr2010-no5-mobile-plant-for-reclamation-restoration-or-improvement-of-land                                             |
#      | Mobile plant for land-spreading or treatment                                           | SR2008 No 27        | 2,641 | https://www.gov.uk/government/publications/standard-rules-sr2008-number-27                                                                                        |
#      | Mobile plant for land-spreading or treatment                                           | SR2010 No 11        | 2,641 | https://www.gov.uk/government/publications/sr2010-number-11                                                                                                       |
      | Storage or treatment of waste - recycling, dredgings, clinical, soil or wood treatment | SR2015 No 21        | 3,926 | https://www.gov.uk/government/publications/sr2015-no21-75kte-materials-recycling-facility                                                                         |
      | Storage or treatment of waste - recycling, dredgings, clinical, soil or wood treatment | SR2010 No 18        | 2,641 | https://www.gov.uk/government/publications/sr2010-no18-storage-and-treatment-of-dredgings-for-recovery                                                            |
      | Storage or treatment of waste - recycling, dredgings, clinical, soil or wood treatment | SR2010 No 17        | 2,641 | https://www.gov.uk/government/publications/sr2010-no17-storage-of-digestate-from-anaerobic-digestion-plants                                                       |
      | Storage or treatment of waste - recycling, dredgings, clinical, soil or wood treatment | SR2013 No 1         | 2,641 | https://www.gov.uk/government/publications/sr2013-no-1-treatment-of-100-ty-of-clinical-and-healthcare-waste                                                       |
      | Storage or treatment of waste - recycling, dredgings, clinical, soil or wood treatment | SR2010 No 12        | 2,641 | https://www.gov.uk/government/publications/sr2010-number-12                                                                                                       |
      | Storage or treatment of waste - recycling, dredgings, clinical, soil or wood treatment | SR2015 No 23        | 3,926 | https://www.gov.uk/government/publications/sr2015-no23-treatment-of-waste-wood-for-recovery                                                                       |
      | Storage or treatment of waste - recycling, dredgings, clinical, soil or wood treatment | SR2015 No 24        | 3,926 | https://www.gov.uk/government/publications/sr2015-no24-use-of-waste-to-manufacture-timber-or-construction-products                                                |
      | Waste transfer station or amenity site with or without treatment                       | SR2008 No 9         | 2,641 | https://www.gov.uk/government/publications/sr2008-no9-asbestos-waste-transfer-station                                                                             |
      | Waste transfer station or amenity site with or without treatment                       | SR2015 No 4         | 3,926 | https://www.gov.uk/government/publications/sr2015-no4-75kte-household-commercial-and-industrial-waste-transfer-station                                            |
      | Waste transfer station or amenity site with or without treatment                       | SR2015 No 9         | 3,926 | https://www.gov.uk/government/publications/sr2015-no9-household-commercial-and-industrial-waste-transfer-station-with-asbestos-storage-no-building                |
      | Waste transfer station or amenity site with or without treatment                       | SR2015 No 6         | 3,926 | https://www.gov.uk/government/publications/sr2015-no6-75kte-household-commercial-and-industrial-waste-transfer-station-with-treatment                             |
      | Waste transfer station or amenity site with or without treatment                       | SR2015 No 7         | 3,926 | https://www.gov.uk/government/publications/sr2015-no7-household-commercial-and-industrial-waste-transfer-station-with-treatment-no-building                       |
      | Waste transfer station or amenity site with or without treatment                       | SR2015 No 10        | 3,926 | https://www.gov.uk/government/publications/sr2015-no10-75kte-household-commercial-and-industrial-waste-transfer-station-with-treatment-and-asbestos-storage       |
      | Waste transfer station or amenity site with or without treatment                       | SR2015 No 11        | 3,926 | https://www.gov.uk/government/publications/sr2015-no11-household-commercial-and-industrial-waste-transfer-station-with-treatment-and-asbestos-storage-no-building |
      | Waste transfer station or amenity site with or without treatment                       | SR2015 No 20        | 3,926 | https://www.gov.uk/government/publications/sr2015-no20-75kte-non-hazardous-and-hazardous-household-waste-amenity-site                                             |
      | Waste transfer station or amenity site with or without treatment                       | SR2015 No 19        | 3,926 | https://www.gov.uk/government/publications/sr2015-no19-75kte-non-hazardous-household-waste-amenity-site                                                           |
      | Metal recycling, scrap metal and WEEE - not cars or vehicles                           | SR2015 No 3         | 3,926 | https://www.gov.uk/government/publications/sr2015-no3-metal-recycling-and-weee-authorised-treatment-facility-excluding-ozone-depleting-substances                 |
      | Storage or treatment of waste - recycling, dredgings, clinical, soil or wood treatment | SR2015 No 22        | 3,926 | https://www.gov.uk/government/publications/sr2015-no22-materials-recycling-facility-no-building                                                                   |
      | Waste transfer station or amenity site with or without treatment                       | SR2015 No 5         | 3,926 | https://www.gov.uk/government/publications/sr2015-no5-household-commercial-and-industrial-waste-transfer-station-no-building                                      |
      | Waste transfer station or amenity site with or without treatment                       | SR2015 No 8         | 3,926 | https://www.gov.uk/government/publications/sr2015-no8-75kte-household-commercial-and-industrial-waste-transfer-station-with-asbestos-storage                      |

  @wip
  @Smoke_prod
  @Smoke_preprod
  Scenario Outline: As a user, I should be able to download the forms for the offline permit: <Permit>
    Given the application has been launched
    And I start a new application
        #And I select Standard rules as the permit type
    And I select <PermitCategory> as the permit category
    And I select <Permit> as the permit number
    Then I am on <PermitType> apply offline page with <Link> link
    Examples:
      | PermitCategory                                                                         | Permit       | PermitType                                                                                                                                                                | Link                                                                                                                                                 |
      | Composting, sewage or sludge treatment, biogas                                         | SR2012 No 4  | Apply for composting in closed systems - installation - SR2012 No 4                                                                                                       | https://www.gov.uk/government/collections/environmental-permit-application-forms-for-a-standard-permit-installations-mining-waste-or-waste-operation |
      | Composting, sewage or sludge treatment, biogas                                         | SR2012 No 8  | Apply for composting in open systems - installation - SR2012 No 8                                                                                                         | https://www.gov.uk/government/collections/environmental-permit-application-forms-for-a-standard-permit-installations-mining-waste-or-waste-operation |
      | Composting, sewage or sludge treatment, biogas                                         | SR2009 No 3  | Apply for low impact part a installation for the production of biodiesel - SR2009 No 3                                                                                    | https://www.gov.uk/government/collections/environmental-permit-application-forms-for-a-standard-permit-installations-mining-waste-or-waste-operation |
      | Mining, oil and gas                                                                    | SR2009 No 8  | Apply for management of inert wastes and unpolluted soil at mines and quarries - SR2009 No 8                                                                              | https://www.gov.uk/government/collections/environmental-permit-application-forms-for-a-standard-permit-installations-mining-waste-or-waste-operation |
      | Mining, oil and gas                                                                    | SR2015 No 2  | Apply for storage and handling of crude oil from onshore oil and gas - installation - SR2015 No 2                                                                         | https://www.gov.uk/government/collections/environmental-permit-application-forms-for-a-standard-permit-installations-mining-waste-or-waste-operation |
      | Mining, oil and gas                                                                    | SR2015 No 1  | Apply for the management of extractive waste, not including a waste facility, generated from onshore oil and gas prospecting excluding hydraulic fracturing - SR2015 No 1 | https://www.gov.uk/government/collections/environmental-permit-application-forms-for-a-standard-permit-installations-mining-waste-or-waste-operation |
      | Storage or treatment of waste - recycling, dredgings, clinical, soil or wood treatment | SR2009 No 2  | Apply for low impact part a installation for spent ion exchange resins - SR2009 No 2                                                                                      | https://www.gov.uk/government/collections/environmental-permit-application-forms-for-a-standard-permit-installations-mining-waste-or-waste-operation |
      | Storage or treatment of waste - recycling, dredgings, clinical, soil or wood treatment | SR2012 No 13 | Apply for treatment of incinerator bottom ash (iba) - installation - SR2012 No 13                                                                                         | https://www.gov.uk/government/collections/environmental-permit-application-forms-for-a-standard-permit-installations-mining-waste-or-waste-operation |

  @wip
  @Smoke_preprod
  @Smoke_prod
  Scenario Outline: As a user, I should be able to download the forms for the offline permit category: <PermitCategory>
    Given the application has been launched
    And I start a new application
        #And I select Standard rules as the permit type
    And I select <PermitCategory> as the permit category
    Then I am on <PermitType> apply offline page with <Link> link
    Examples:
      | PermitCategory                               | PermitType                                                     | Link                                                                                                             |
      | Flood risk activities                        | Apply for flood risk activities permits                        | https://www.gov.uk/guidance/flood-risk-activities-environmental-permits#standard-rules-permits                   |
      | Water discharges                             | Apply for water discharges permits                             | https://www.gov.uk/government/collections/environmental-permit-application-forms-standard-permit-water-discharge |
      | Radioactive substances for non-nuclear sites | Apply for radioactive substances for non-nuclear sites permits | https://www.gov.uk/government/collections/radioactive-substances-regulation-for-non-nuclear-sites                |

